[package]
name        = "neocom"
description = "ネオ・COM × NEO SYSTEMS"
version     = "0.0.1"
authors     = ["Casey Rodarmor <casey@rodarmor.com>"]
license     = "CC0-1.0"
homepage    = "https://github.com/casey/neocom"
