[package]
name    = "neosys-native"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]

[dependencies]
gl             = "0.10.0"
glutin         = "0.16.0"
neocom-special = {path = "../neocom-special"}
cpal           = "0.8.1"
rand           = "*"
