[package]
name        = "neocom-special"
version     = "0.0.0"
description = "ネオ・SPECIAL"
authors     = ["Casey Rodarmor <casey@rodarmor.com>"]
license     = "CC0-1.0"
homepage    = "https://github.com/casey/neocom"
