[package]
name    = "life"
version = "0.0.0"
authors = ["Casey Rodarmor <casey@rodarmor.com>"]

[dependencies]
neocom-special = {path = "../../neocom-special"}
neosys-native  = {path = "../../neosys-native"}
rand           = "0.5.0"
